### ISSUE TITLE
No sorce downloaded anymore

### ISSUE THREAD

**Issue by yin** [koldbyte/CodeBackup#7]
Hey!

**Comment by rabisankar78** [comment]
What is this.... Backup code

**Comment by koldbyte** [comment]
Yes. I am aware.  I will try to fix it as soon as possible. I have been very busy with my work lately. Sorry.
If anyone wants to chime in, contributions are most welcome.

**Comment by koldbyte** [comment]
[Please try the latest here](https://github.com/koldbyte/CodeBackup/releases/latest)
