### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by iamnishantrai** [koldbyte/CodeBackup#8]
On running the .jar file and selecting all options and providing the handle, when run button is clicked, it's fetching nothing.

**Comment by koldbyte** [comment]
I have some made fixes for Codechef. Codeforces and Spoj seems to be working.

@iamnishantrai , Please try the new release and let me know if there are any issues or any feature requests. [Get latest release from here.](https://github.com/koldbyte/CodeBackup/releases/latest)
